### ISSUE TITLE
IE9 Object doesn't support property or method 'defineAttribute' 

### ISSUE THREAD

**Issue by aspexi** [chemerisuk/better-placeholder-polyfill#4]
"SCRIPT438: Object doesn't support property or method 'defineAttribute' 
better-placeholder-polyfill.js?ver=1, line 31 character 13"

Any ideas how to fix?

**Comment by chemerisuk** [comment]
@aspexi check your better-dom version. Should be the 2.1.0+

**Comment by aspexi** [comment]
@chemerisuk thanks. It's 2.1.4. I guess it's a potential conflict with some other js plugins I'm using. Anyway, do you have any other ideas maybe?

**Comment by chemerisuk** [comment]
@aspexi make sure that IE is not in the compatibility mode

**Comment by aspexi** [comment]
@chemerisuk due to time pressure I had to use another library, anyway many thanks for support!
